# Generated by Django 2.0.7 on 2018-08-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('NotSet', 'NotSet'), ('Male', 'Male'), ('Female', 'Female')], default='NotSet', max_length=50),
        ),
    ]
