# Generated by Django 2.1 on 2018-09-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yomarket', '0002_auto_20180903_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('redeemed', 'redeemed coupons for offer/shop'), ('taken', 'taken coupons for offer/shop'), ('liked', 'likes for offer/shop'), ('shown', 'views for offer/shop')], default='email', max_length=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yomarket.Offer')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yomarket.Shop')),
            ],
            options={
                'verbose_name': 'statistic',
            },
        ),
    ]
