# Generated by Django 2.0.7 on 2018-08-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0003_auto_20180803_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('-created',)},
        ),
    ]
