# Generated by Django 2.0.7 on 2018-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0004_auto_20180806_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='codes_count',
            field=models.SmallIntegerField(default=0, verbose_name='codes count'),
        ),
        migrations.AddField(
            model_name='offer',
            name='expire',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expire date'),
        ),
    ]
