# Generated by Django 2.0.7 on 2018-08-08 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0006_shop_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_offer', to='yomarket.Shop'),
        ),
    ]
