# Generated by Django 2.0.7 on 2018-08-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0008_auto_20180809_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcoupon',
            options={'verbose_name': 'QRcoupon', 'verbose_name_plural': 'QRcoupons'},
        ),
        migrations.RemoveField(
            model_name='qrcoupon',
            name='user',
        ),
    ]
