# Generated by Django 2.0.7 on 2018-08-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0009_auto_20180810_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcoupon',
            name='available',
        ),
        migrations.AddField(
            model_name='qrcoupon',
            name='in_transaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrcoupon',
            name='redmeeded',
            field=models.BooleanField(default=False),
        ),
    ]
