# Generated by Django 2.0.7 on 2018-08-13 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0010_auto_20180810_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcoupon',
            name='short_uuid',
            field=models.CharField(default='<django.', editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='qrcoupon',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
