# Generated by Django 2.0.7 on 2018-08-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0011_auto_20180813_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcoupon',
            name='short_uuid',
            field=models.CharField(default='<django.', editable=False, max_length=8),
        ),
    ]
