# Generated by Django 2.0.7 on 2018-08-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0012_auto_20180813_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcoupon',
            old_name='uuid',
            new_name='uuid_id',
        ),
    ]
