# Generated by Django 2.0.7 on 2018-08-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0013_auto_20180813_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcoupon',
            name='short_uuid',
        ),
    ]
