# Generated by Django 2.0.7 on 2018-08-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0014_remove_qrcoupon_short_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcoupon',
            old_name='redmeeded',
            new_name='is_redeemed',
        ),
    ]
