# Generated by Django 2.0.7 on 2018-08-13 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0015_auto_20180813_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcoupon',
            name='transaction_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
