# Generated by Django 2.0.7 on 2018-08-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0016_qrcoupon_transaction_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qrcode',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AlterField(
            model_name='qrcoupon',
            name='transaction_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
