# Generated by Django 2.0.7 on 2018-08-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0020_auto_20180820_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, upload_to='shops/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='shop',
            name='outer_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
