# Generated by Django 2.0.7 on 2018-08-22 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0022_auto_20180821_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shops_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
