# Generated by Django 2.0.7 on 2018-08-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0024_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='code_type',
            field=models.CharField(choices=[('QRCODE', 'QRCODE'), ('BARCODE', 'BARCODE'), ('ALPHANUMCODE', 'ALPHANUMCODE')], default='QRCODE', max_length=50),
        ),
    ]
