# Generated by Django 2.0.7 on 2018-08-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0025_shop_code_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='code_type',
            field=models.CharField(choices=[('QRCODE', 'QR code'), ('BARCODE', 'Barcode'), ('ALPHANUMCODE', 'Alphanumeric code')], default='QRCODE', max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='code_type',
            field=models.CharField(choices=[('QRCODE', 'QR code'), ('BARCODE', 'Barcode'), ('ALPHANUMCODE', 'Alphanumeric code')], default='QRCODE', max_length=50),
        ),
    ]
