# Generated by Django 2.0.7 on 2018-08-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0026_auto_20180828_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('DAILY', 'Daily')], default='REGULAR', max_length=50),
        ),
    ]
