# Generated by Django 2.0.7 on 2018-08-30 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yomarket', '0027_offer_offer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcoupon',
            name='in_transaction',
        ),
        migrations.RemoveField(
            model_name='qrcoupon',
            name='transaction_start_time',
        ),
        migrations.AddField(
            model_name='offer',
            name='redeemed_codes_count',
            field=models.SmallIntegerField(default=0, verbose_name='redeemed count'),
        ),
        migrations.AddField(
            model_name='qrcoupon',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrcoupon',
            name='type',
            field=models.CharField(choices=[('QRCODE', 'QR code'), ('BARCODE', 'Barcode'), ('ALPHANUMCODE', 'Alphanumeric code')], default='QRCODE', max_length=50),
        ),
        migrations.AddField(
            model_name='qrcoupon',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
