# Generated by Django 2.1 on 2018-08-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0017_auto_20180820_1138'),
        ('notification', '0002_auto_20180821_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='offer',
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_filter',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_value',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_shop', to='yomarket.Shop'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('category', 'Category'), ('shop', 'Shop')], max_length=8),
        ),
    ]
