# Generated by Django 2.0.7 on 2018-08-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20180827_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email-msg'), ('push', 'Push-msg')], default='email', max_length=5),
        ),
    ]
