ERROR_API = {
    "101": (101, "Unable to log in with provided credentials."),
    "102": (102, "User with this username already exists."),
    "103": (103, "User with this email already exists."),
    "104": (104, "User does not exists"),
    "105": (105, 'Must include "email" and "password".'),
    "106": (106, 'Must include "email".'),
    "107": (107, "Unable to log in with ADMIN role."),
    "108": (108, "Unable to log in with CUSTOMER role."),
    "109": (109, "You must have to log out first"),
    "110": (110, "Already registered"),
    "111": (111, "Unable to login via google account, wrong issuer"),
    "112": (112, "Unable to login via facebook account, wrong issuer id"),
    "113": (113, "Confirmation token not found"),
    "114": (114, "Confirmation token expired"),
    "115": (115, "You must have to login first"),
    "116": (116, "Not logged as owner or manager"),
    "117": (117, "Incorrect user role"),
    "118": (118, "Authentication credentials were not provided."),
    "119": (119, "Invalid token."),
    "120": (120, "Unable to login via social or wrong ID"),
    "121": (121, "Twitter credentials error"),
    "122": (122, "Users not found"),
    "123": (123, "Message delivery error"),
    "124": (124, "Invalid page."),
    "125": (125, "Card already registered"),
    "126": (126, "User not active."),
    "127": (127, "User mismatch."),

    "151": (151, "This password is too short. It must contain at least 8 characters."),
    "152": (152, "This password is too common."),
    "153": (153, "This password is entirely numeric."),

    "161": (161, "The submitted data was not a file. Check the encoding type on the form."),
    "162": (162, "Date has wrong format. Use one of these formats instead: YYYY[-MM[-DD]]."),
    "163": (163, "Wrong data entered"),
    "164": (164, "Wrong cardholder. Permission denied."),
    "165": (165, "No card found."),

    "200": (200, "No coupons"),
    "201": (201, "No history data"),
    "202": (202, "No secondary info data"),
	"203": (203, "No transactions"),
    "204": (204, "No offers"),
    "205": (205, "No daily offers"),
    "206": (206, "No regular offers"),
    "207": (207, "Offer not found"),
    "208": (208, "Invalid code or no coupon"),
    "210": (210, "Cart is empty"),
    "211": (211, "No coupons available"),

    "251": (251, "Shops not found"),

    "305": (305, "Registered.Please verify email"),

    "500": (500, "Ok"),

    "900": (900, "Payment error"),
    "901": (901, "Amount mismatch"),
    "902": (902, "Coupon provided but no discount sum"),
    "903": (903, "Transaction cancellation error."),
    "905": (905, "Transaction successfully cancelled"),

}


PAYMENT_ERRORS = {
    "001":(1, "Blocked confiscate card."),
    "002":(2, "Stolen confiscate card."),
    "003":(3, "Contact credit company."),
    "004":(4, "Refusal."),
    "005":(5, "Forged. confiscate card."),
    "006":(6, "Identity Number of CVV incorrect."),
    "007":(7, "Must contact Credit Card Company"),
    "008":(8, '''Fault in building of access key to blocked cards file.'''),
    "009":(9, "Contact unsuccessful."),
    "010":(10, "Program ceased by user instruction (ESC)."),
    "011":(11, "No confirmation for the ISO currency clearing."),
    "012":(12, "No confirmation for the ISO currency type."),
    "013":(13, "No confirmation for charge/discharge transaction."),
    "014":(14, "Unsupported card"),
    "015":(15, "Number Entered and Magnetic Strip do not match"),
    "017":(17, "Last 4 digets not entered"),
    "019":(19, "Record in INT_IN shorter than 16 characters."),
    "020":(20, "Input file (INT_IN) does not exist."),
    "021":(21, "Blocked cards file (NEG) non-existent or has not been updated - execute transmission or request authorization for each transaction."),
    "022":(22, "One of the parameter files or vectors do not exist."),
    "023":(23, "Date file (DATA) does not exist."),
    "024":(24, "Format file (START) does not exist."),
    "025":(25, "Difference in days in input of blocked cards is too large - execute transmission or request authorization for each transaction."),
    "026":(26, "Difference in generations in input of blocked cards is too large - execute transmission or request authorization for each transaction."),
    "027":(27, "Where the magnetic strip is not completely entered"),
    "028":(28, "Central terminal number not entered into terminal defined for work as main supplier."),
    "029":(29, "Beneficiary number not entered into terminal defined as main beneficiary."),
    "030":(30, "Terminal not updated as main supplier/beneficiary and supplier/beneficiary number entered."),
    "031":(31, "Terminal updated as main supplier and beneficiary number entered"),
    "032":(32, "Old transactions - carry out transmission or request authorization for each transaction."),
    "033":(33, "Defective card"),
    "034":(34, "Card not permitted for this terminal or no authorization for this type of transaction."),
    "035":(35, "Card not permitted for transaction or type of credit."),
    "036":(36, "Expired."),
    "037":(37, "Error in instalments - Amount of transaction needs to be equal to the first instalment + (fixed instalments times no. of instalments)"),
    "038":(38, "Cannot execute transaction in excess of credit card ceiling for immediate debit."),
    "039":(39, "Control number incorrect."),
    "040":(40, "Terminal defined as main beneficiary and supplier number entered."),
    "041":(41, "Exceeds ceiling where input file contains J1 or J2 or J3 (contact prohibited)."),
    "042":(42, "Card blocked for supplier where input file contains J1 or J2 or J3 (contact prohibited)."),
    "043":(43, "Random where input file contains J1 (contact prohibited)."),
    "044":(44, "Terminal prohibited from requesting authorization without transaction (J5)"),
    "045":(45, "Terminal prohibited for supplier-initiated authorization request (J6)"),
    "046":(46, "Terminal must request authorization where input file contains J1 or J2 or J3 (contact prohibited)."),
    "047":(47, "Secret code must be entered where input file contains J1 or J2 or J3 (contact prohibited)."),
    "051":(51, "Vehicle number defective."),
    "052":(52, "Distance meter not entered."),
    "053":(53, "Terminal not defined as gas station. (petrol card passed or incorrect transaction code)."),
    "057":(57, "Identity Number Not Entered"),
    "058":(58, "CVV2 Not Entered"),
    "059":(59, "Identiy Number and CVV2 Not Entered"),
    "060":(60, "ABS attachment not found at start of input data in memory."),
    "061":(61, "Card number not found or found twice"),
    "062":(62, "Incorrect transaction type"),
    "063":(63, "Incorrect transaction code."),
    "064":(64, "Type of credit incorrect."),
    "065":(65, "Incorrect currency."),
    "066":(66, "First instalment and/or fixed payment exists for non-instalments type of credit."),
    "067":(67, "Number of instalments exists for type of credit not requiring this."),
    "068":(68, "Linkage to dollar or index not possible for credit other than instalments."),
    "069":(69, "Length of magnetic strip too short."),
    "070":(70, "PIN terminal not defined"),
    "071":(71, "PIN must be enetered"),
    "072":(72, "Secret code not entered."),
    "073":(73, "Incorrect secret code."),
    "074":(74, "Incorrect secret code - last try."),
    "079":(79, "Currency is not listed in vector 59."),
    "080":(80, '''Club code" entered for unsuitable credit type'''),
    "090":(90, "Transaction cancelling is not allowed for this card."),
    "091":(91, "Transaction cancelling is not allowed for this card."),
    "092":(92, "Transaction cancelling is not allowed for this card."),
    "099":(99, "Cannot read/write/open TRAN file."),
    "100":(100, "No equipment for inputting secret code."),
    "101":(101, "No authorization from credit company for work."),
    "107":(107, "Transaction amount too large - split into a number of transactions."),
    "108":(108, "Terminal not authorized to execute forced actions."),
    "109":(109, "Terminal not authorized for card with service code 587."),
    "110":(110, "Terminal not authorized for immediate debit card."),
    "111":(111, "Terminal not authorized for instalments transaction."),
    "112":(112, "Terminal not authorized for telephone/signature only instalments transaction."),
    "113":(113, "Terminal not authorized for telephone transaction."),
    "114":(114, '''Terminal not authorized for "signature only" transaction.'''),
    "115":(115, "Terminal not authorized for dollar transaction."),
    "116":(116, "Terminal not authorized for club transaction."),
    "117":(117, "Terminal not authorized for stars/points/miles transaction."),
    "118":(118, "Terminal not authorized for Isracredit credit."),
    "119":(119, "Terminal not authorized for Amex Credit credit."),
    "120":(120, "Terminal not authorized for dollar linkage."),
    "121":(121, "Terminal not authorized for index linkage."),
    "122":(122, "Terminal not authorized for index linkage with foreign cards."),
    "123":(123, "Terminal not authorized for stars/points/miles transaction for this type of credit."),
    "124":(124, "Terminal not authorized for Isracredit payments."),
    "125":(125, "Terminal not authorized for Amex payments."),
    "126":(126, "Terminal not authorized for this club code."),
    "127":(127, "Terminal not authorized for immediate debit transaction except for immediate debit cards."),
    "128":(128, "Terminal not authorized to accept Visa card staring with 3."),
    "129":(129, "Terminal not authorized to execute credit transaction above the ceiling."),
    "130":(130, "Card not permitted for execution of club transaction."),
    "131":(131, "Card not permitted for execution stars/points/miles transaction."),
    "132":(132, "Card not permitted for execution of dollar transactions (regular or telephone)."),
    "133":(133, "Card not valid according Isracard list of valid cards."),
    "134":(134, "Defective card according to system definitions (Isracard VECTOR1) - no. of figures on card - error."),
    "135":(135, "Card not permitted to execute dollar transactions according to system definition (Isracard VECTOR1)."),
    "136":(136, "Card belongs to group not permitted to execute transactions according to system definition (Visa VECTOR 20)."),
    "137":(137, "Card prefix (7 figures) invalid according to system definition (Diners VECTOR21)"),
    "138":(138, "Card not permitted to carry out instalments transaction according to Isracard list of valid cards."),
    "139":(139, "Number of instalments too large according to Isracard list of valid cards."),
    "140":(140, "Visa and Diners cards not permitted for club instalments transactions."),
    "141":(141, "Series of cards not valid according to system definition (Isracard VECTOR5)."),
    "142":(142, "Invalid service code according to system definition (Isracard VECTOR6)."),
    "143":(143, "Card prefix (2 figures) invalid according to system definition (Isracard VECTOR7)."),
    "144":(144, "Invalid service code according to system definition (Visa VECTOR12)."),
    "145":(145, "Invalid service code according to system definition (Visa VECTOR13)."),
    "146":(146, "Immediate debit card prohibited for execution of credit transaction."),
    "147":(147, "Card not permitted to execute instalments transaction according to Leumicard vector no. 31."),
    "148":(148, "Card not permitted for telephone and signature only transaction according to Leumicard vector no. 31"),
    "149":(149, "Card not permitted for telephone transaction according to Leumicard vector no. 31"),
    "150":(150, "Credit not approved for immediate debit cards."),
    "151":(151, "Credit not approved for foreign cards."),
    "152":(152, "Club code incorrect."),
    "153":(153, "Card not permitted to execute flexible credit transactions (Adif/30+) according to system definition (Diners VECTOR21)."),
    "154":(154, "Card not permitted to execute immediate debit transactions according to system definition (Diners VECTOR21)."),
    "155":(155, "Amount of payment for credit transaction too small."),
    "156":(156, "Incorrect number of instalments for credit transaction"),
    "157":(157, "0 ceiling for this type of card for regular credit or Credit transaction."),
    "158":(158, "0 ceiling for this type of card for immediate debit credit transaction"),
    "159":(159, "0 ceiling for this type of card for immediate debit in dollars."),
    "160":(160, "0 ceiling for this type of card for telephone transaction."),
    "161":(161, "0 ceiling for this type of card for credit transaction."),
    "162":(162, "0 ceiling for this type of card for instalments transaction."),
    "163":(163, "American Express card issued abroad not permitted for instalments transaction."),
    "164":(164, "JCB cards permitted to carry out regular credit transactions."),
    "165":(165, "Amount in stars/points/miles larger than transaction amount."),
    "166":(166, "Club card not in terminal range."),
    "167":(167, "Stars/points/miles transaction cannot be executed."),
    "168":(168, "Dollar transaction cannot be executed for this type of card."),
    "169":(169, "Credit transaction cannot be executed with other than regular credit."),
    "170":(170, "Amount of discount on stars/points/miles greater than permitted."),
    "171":(171, "Forced transaction cannot be executed with credit/immediate debut card."),
    "172":(172, "Previous transaction cannot be cancelled (credit transaction or card number not identical)."),
    "173":(173, "Double transaction."),
    "174":(174, "Terminal not permitted for index linkage for this type of credit."),
    "175":(175, "Terminal not permitted for dollar linkage for this type of credit."),
    "176":(176, "Card invalid according to system definition (Isracard VECTOR1)"),
    "177":(177, '''Cannot execute "Self-Service" transaction at gas stations except at "Self-Service at gas stations".'''),
    "178":(178, "Credit transaction forbidden with stars/points/miles."),
    "179":(179, "Dollar credit transaction forbidden on tourist card."),
    "180":(180, "Club Card can not preform Telephone Transactions"),
    "200":(200, "Application error."),
    "700":(700, "Approved TEST Masav transaction"),
    "701":(701, "Invalid Bank Number"),
    "702":(702, "Invalid Branch Number"),
    "703":(703, "Invalid Account Number"),
    "704":(704, "Incorrect Bank/Branch/Account Combination"),
    "705":(705, "Application Error"),
    "706":(706, "Supplier directory does not exist"),
    "707":(707, "Supplier configuration does not exist"),
    "708":(708, "Charge amount zero or negative"),
    "709":(709, "Invalid configuration file"),
    "710":(710, "Invalid date format"),
    "711":(711, "DB Error"),
    "712":(712, "Required parameter is missing"),
    "800":(800, "Transaction Canceled"),
    "900":(900, "3D Secure Failed"),
    "903":(903, "Fraud suspected"),
    "951":(951, "PayPal Protocol Error"),
    "952":(952, "PayPal Payment not completed"),
    "954":(954, "PayPal Payment Failed"),
    "955":(955, "PayPal Payment status error"),
    "959":(959, "PayPal Payment completed unsuccessfully"),
    "960":(960, "General Request Error"),
    "961":(961, "General Authorization Error"),
    "962":(962, "General Tokenization Error"),
    "963":(963, "General DB Error"),
    "964":(964, "General Action Error"),

}



#100 - 199 - users API errors
#151 - 160 - password errors
#161 - 170 - profile errors

#200 - 299 - offers API errors
#251 - 270 - shops errors