# Generated by Django 2.0.7 on 2018-08-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20180806_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creator_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
