# Generated by Django 2.0.7 on 2018-08-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_user_creator_id'),
        ('common', '0009_auto_20180813_1023'),
    ]

    operations = [
    ]
