# Generated by Django 2.1 on 2018-08-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_merge_20180814_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
