# Generated by Django 2.1 on 2018-08-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_user_fb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fb_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
