# Generated by Django 2.0.7 on 2018-08-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20180820_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
